<?php

namespace PHPRanker\Checkstyle;

use PHPRanker\AbstractViolation;

class Violation extends AbstractViolation
{
    private $default = 70000;
    private $sniffs  = [
        "Array"                       => 60000,
        "ClassDefinitionNameSpacing"  => 50000,
        "ColourDefinition"            => 50000,
        "ClassCreateInstance"         => 60000,
        "ClassDeclaration"            => 60000,
        "FullyQualifiedNamespace"     => 50000,
        "InterfaceName"               => 50000,
        "UnusedUseStatement"          => 50000,
        "ClassComment"                => 50000,
        "DocComment"                  => 60000,
        "DocCommentStar"              => 50000,
        "FileComment"                 => 60000,
        "FunctionComment"             => 60000,
        "HookComment"                 => 50000,
        "InlineComment"               => 60000,
        "PostStatementComment"        => 50000,
        "ControlSignature"            => 50000,
        "ElseIf"                      => 50000,
        "InlineControlStructure"      => 50000,
        "EndFileNewline"              => 50000,
        "FileEncoding"                => 50000,
        "LineLength"                  => 50000,
        "TxtFileLineLength"           => 50000,
        "MultiLineAssignment"         => 60000,
        "SpaceInlineIf"               => 60000,
        "SpaceUnaryOperator"          => 50000,
        "DiscouragedFunctions"        => 50000,
        "FunctionDeclaration"         => 60000,
        "AutoAddedKeys"               => 50000,
        "ClassFiles"                  => 60000,
        "DuplicateEntry"              => 60000,
        "Required"                    => 60000,
        "ValidClassName"              => 60000,
        "ValidFunctionName"           => 60000,
        "ValidGlobal"                 => 60000,
        "ValidVariableName"           => 60000,
        "ConstantName"                => 50000,
        "EmptyInstall"                => 60000,
        "FunctionAlias"               => 60000,
        "FunctionT"                   => 50000,
        "FunctionWatchdog"            => 60000,
        "InstallHooks"                => 60000,
        "LStringTranslatable"         => 60000,
        "PregSecurity"                => 60000,
        "RemoteAddress"               => 60000,
        "TInHookMenu"                 => 60000,
        "TInHookSchema"               => 60000,
        "UnnecessaryStringConcat"     => 60000,
        "CloseBracketSpacing"         => 50000,
        "Comma"                       => 50000,
        "EmptyLines"                  => 60000,
        "Namespace"                   => 50000,
        "ObjectOperatorIndent"        => 60000,
        "ObjectOperatorSpacing"       => 50000,
        "OpenBracketSpacing"          => 50000,
        "OperatorSpacing"             => 50000,
        "ScopeClosingBrace"           => 50000,
        "ScopeIndent"                 => 50000,
        "VariableAnalysis"            => 50000,
        "AuthorTag"                   => 50000,
        "CommentEmptyLine"            => 50000,
        "CheckPlain"                  => 50000,
        "CurlSslVerifier"             => 50000,
        "DbQuery"                     => 50000,
        "DbSelectBraces"              => 50000,
        "DefaultValueSanitize"        => 50000,
        "FormErrorT"                  => 50000,
        "LCheckPlain"                 => 50000,
        "MessageT"                    => 50000,
        "TCheckPlain"                 => 50000,
        "Theme"                       => 50000,
        "VariableSetSanitize"         => 50000,
        "AccessHookMenu"              => 50000,
        "FormAlterDoc"                => 50000,
        "HookInitCss"                 => 50000,
        "InstallT"                    => 50000,
        "AccessAdminPages"            => 50000,
        "ClassName"                   => 50000,
        "DescriptionT"                => 50000,
        "FormStateInput"              => 50000,
        "LanguageNone"                => 50000,
        "OptionsT"                    => 50000,
        "VariableName"                => 50000,
        "NotAllowed"                  => 60000,
        "InvalidEOLChar"              => 60000,
        "TooLong"                     => 60000,
        "NoSpaceAfterComma"           => 50000,
        "TabsUsed"                    => 60000,
        "Incorrect"                   => 50000,
        "IncorrectExact"              => 50000,
        "NotAtEnd"                    => 60000,
        "MissingNamespace"            => 600000,
        "MultipleClasses"             => 400000,
        "FoundWithSymbols"            => 500000,
        "SpacingAfterOpenBrace"       => 50000,
        "NotAllowed"                  => 50000,
        "TerminatingComment"          => 50000,
        "NotAllowed"                  => 50000,
        "NoneFound"                   => 50000,
        "CloseBracketLine"            => 50000,
        "ContentAfterOpenBracket"     => 50000,
        "Indent"                      => 50000,
        "MultipleArguments"           => 70000,
        "SpaceAfterOpenBracket"       => 50000,
        "SpaceBeforeCloseBracket"     => 50000,
        "SpaceBeforeOpenBracket"      => 50000,
        "NotCamelCaps"                => 50000,
        "NewlineAfterOpenBrace"       => 50000,
        "SpaceAfterCloseBrace"        => 50000,
        "SpaceAfterCloseParenthesis"  => 50000,
        "SpaceAfterKeyword"           => 50000,
        "SpaceBeforeSemicolon"        => 50000,
        "NoSpaceAfterFirst"           => 50000,
        "NoSpaceAfterSecond"          => 50000,
        "NoSpaceBeforeArg"            => 50000,
        "BraceOnSameLine"             => 50000,
        "ContentAfterBrace"           => 50000,
        "ContentBefore"               => 50000,
        "Indent"                      => 50000,
        "EndLine"                     => 50000,
        "ArrayAssignmentRestrictions" => 50000,
        "ArrayDeclaration"            => 50000,
        "ArrayKeySpacingRestrictions" => 50000,
        "NonceVerification"           => 50000,
        "ValidClassName"              => 50000,
        "FileName"                    => 50000,
        "FunctionRestrictions"        => 50000,
        "ValidFunctionName"           => 50000,
        "ValidVariableName"           => 50000,
        "DiscouragedFunctions"        => 50000,
        "StrictComparisons"           => 50000,
        "StrictInArray"               => 50000,
        "YodaConditions"              => 50000,
        "AdminBarRemoval"             => 50000,
        "CronInterval"                => 50000,
        "DirectDatabaseQuery"         => 50000,
        "FileSystemWritesDisallow"    => 50000,
        "OrderByRand"                 => 50000,
        "PluginMenuSlug"              => 50000,
        "PostsPerPage"                => 50000,
        "RestrictedFunctions"         => 50000,
        "RestrictedVariables"         => 50000,
        "SessionFunctionsUsage"       => 50000,
        "SessionVariableUsage"        => 50000,
        "SlowDBQuery"                 => 50000,
        "SuperGlobalInputUsage"       => 50000,
        "TimezoneChange"              => 50000,
        "ValidatedSanitizedInput"     => 50000,
        "GlobalVariables"             => 50000,
        "VariableRestrictions"        => 50000,
        "EnqueuedResources"           => 50000,
        "PreparedSQL"                 => 50000,
        "CastStructureSpacing"        => 50000,
        "ControlStructureSpacing"     => 50000,
        "OperatorSpacing"             => 50000,
        "EscapeOutput"                => 50000,
    ];

    public function addViolation(array $nodes)
    {
        $category = $nodes["category"];
        $type     = $nodes["type"];

        if (isset($this->sniffs[$category])) {
            $this->remediation = $this->sniffs[$category];
        } elseif (isset($this->sniffs[$type])) {
            $this->remediation = $this->sniffs[$type];
        } elseif ($category && $type) {
            $this->remediation = $this->default;
        }

        return $this;
    }
}
